In [1]:
import org.apache.spark.mllib.linalg.{Vector, Vectors, Matrices}

In [2]:
import org.apache.spark.mllib.linalg.distributed.RowMatrix

In [3]:
def transpose(m: Array[Array[Double]]): Array[Array[Double]] = {
    (for {
        c <- m(0).indices
    } yield m.map(_(c)) ).toArray
  }

In [4]:
val file = sc.textFile("hdfs://localhost:9000/user/hadoop/matriz_n8")

In [5]:
val rows = file.map{line => 
    val values = line.split(' ').map(x=>(x.replace(",","").replace("[","").replace("]",""))).map(_.toDouble)
    Vectors.sparse(values.length, values.zipWithIndex.map(e=>(e._2, e._1)).filter(_._2 != 0.0))
}

In [6]:
file.take(2)

Array([572, 448, 125, 644, 458, 538, 792, 157, 800, 150, 983, 929, 337, 719, 344, 726, 674, 779, 668, 591], [586, 168, 381, 687, 609, 682, 306, 481, 380, 777, 301, 115, 775, 917, 97, 396, 568, 25, 151, 5])

Array([572, 448, 125, 644, 458, 538, 792, 157, 800, 150, 983, 929, 337, 719, 344, 726, 674, 779, 668, 591], [586, 168, 381, 687, 609, 682, 306, 481, 380, 777, 301, 115, 775, 917, 97, 396, 568, 25, 151, 5])

In [7]:
rows.take(2)

Array((20,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],[572.0,448.0,125.0,644.0,458.0,538.0,792.0,157.0,800.0,150.0,983.0,929.0,337.0,719.0,344.0,726.0,674.0,779.0,668.0,591.0]), (20,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],[586.0,168.0,381.0,687.0,609.0,682.0,306.0,481.0,380.0,777.0,301.0,115.0,775.0,917.0,97.0,396.0,568.0,25.0,151.0,5.0]))

Array((20,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],[572.0,448.0,125.0,644.0,458.0,538.0,792.0,157.0,800.0,150.0,983.0,929.0,337.0,719.0,344.0,726.0,674.0,779.0,668.0,591.0]), (20,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],[586.0,168.0,381.0,687.0,609.0,682.0,306.0,481.0,380.0,777.0,301.0,115.0,775.0,917.0,97.0,396.0,568.0,25.0,151.0,5.0]))

In [8]:
val rmat = new RowMatrix(rows)

In [9]:
val file2 = sc.textFile("hdfs://localhost:9000/user/hadoop/matriz_n9")

In [10]:
val dm1 = file2.map { line =>
    val values = line.split(' ').map(x=>(x.replace(",","").replace("[","").replace("]",""))).map(_.toDouble)
    Vectors.dense(values)
}

In [11]:
// val dm = transpose(dm1)

Name: Syntax Error.
Message: 
StackTrace: 

Name: Syntax Error.
Message: 
StackTrace: 

In [12]:
file2.take(2)

Array([688, 890, 591, 442, 69, 181, 150, 262, 908, 759, 76, 558, 775, 735, 465, 433, 709, 813, 384, 455, 212, 893, 214, 899, 915, 368, 151, 463, 604, 588, 702, 221, 893, 496, 57, 924, 83, 803, 960, 287, 571, 846, 655, 736, 545, 270, 714, 976, 278, 950, 848, 114, 693, 714, 758, 627, 521, 665, 617, 522, 203, 7, 914, 928, 20, 824, 975, 377, 369, 540, 778, 113, 190, 999, 25, 203, 756, 917, 898, 645, 654, 780, 960, 977, 423, 133, 993, 535, 694, 515, 833, 170, 427, 421, 489, 220, 166, 705, 268, 267, 370, 55, 597, 781, 472, 205, 597, 61, 288, 293, 855, 279, 946, 353, 165, 13, 276, 350, 6, 19, 836, 480, 748, 927, 994, 968, 774, 538, 465, 330, 384, 347, 357, 566, 870, 188, 360, 538, 931, 284, 199, 832, 451, 988, 187, 492, 989, 763, 109, 936, 972, 637, 404, 380, 726, 29, 897...

Array([688, 890, 591, 442, 69, 181, 150, 262, 908, 759, 76, 558, 775, 735, 465, 433, 709, 813, 384, 455, 212, 893, 214, 899, 915, 368, 151, 463, 604, 588, 702, 221, 893, 496, 57, 924, 83, 803, 960, 287, 571, 846, 655, 736, 545, 270, 714, 976, 278, 950, 848, 114, 693, 714, 758, 627, 521, 665, 617, 522, 203, 7, 914, 928, 20, 824, 975, 377, 369, 540, 778, 113, 190, 999, 25, 203, 756, 917, 898, 645, 654, 780, 960, 977, 423, 133, 993, 535, 694, 515, 833, 170, 427, 421, 489, 220, 166, 705, 268, 267, 370, 55, 597, 781, 472, 205, 597, 61, 288, 293, 855, 279, 946, 353, 165, 13, 276, 350, 6, 19, 836, 480, 748, 927, 994, 968, 774, 538, 465, 330, 384, 347, 357, 566, 870, 188, 360, 538, 931, 284, 199, 832, 451, 988, 187, 492, 989, 763, 109, 936, 972, 637, 404, 380, 726, 29, 897...

In [13]:
dm1.take(2)

Array([688.0,890.0,591.0,442.0,69.0,181.0,150.0,262.0,908.0,759.0,76.0,558.0,775.0,735.0,465.0,433.0,709.0,813.0,384.0,455.0,212.0,893.0,214.0,899.0,915.0,368.0,151.0,463.0,604.0,588.0,702.0,221.0,893.0,496.0,57.0,924.0,83.0,803.0,960.0,287.0,571.0,846.0,655.0,736.0,545.0,270.0,714.0,976.0,278.0,950.0,848.0,114.0,693.0,714.0,758.0,627.0,521.0,665.0,617.0,522.0,203.0,7.0,914.0,928.0,20.0,824.0,975.0,377.0,369.0,540.0,778.0,113.0,190.0,999.0,25.0,203.0,756.0,917.0,898.0,645.0,654.0,780.0,960.0,977.0,423.0,133.0,993.0,535.0,694.0,515.0,833.0,170.0,427.0,421.0,489.0,220.0,166.0,705.0,268.0,267.0,370.0,55.0,597.0,781.0,472.0,205.0,597.0,61.0,288.0,293.0,855.0,279.0,946.0,353.0,165.0,13.0,276.0,350.0,6.0,19.0,836.0,480.0,748.0,927.0,994.0,96...

Array([688.0,890.0,591.0,442.0,69.0,181.0,150.0,262.0,908.0,759.0,76.0,558.0,775.0,735.0,465.0,433.0,709.0,813.0,384.0,455.0,212.0,893.0,214.0,899.0,915.0,368.0,151.0,463.0,604.0,588.0,702.0,221.0,893.0,496.0,57.0,924.0,83.0,803.0,960.0,287.0,571.0,846.0,655.0,736.0,545.0,270.0,714.0,976.0,278.0,950.0,848.0,114.0,693.0,714.0,758.0,627.0,521.0,665.0,617.0,522.0,203.0,7.0,914.0,928.0,20.0,824.0,975.0,377.0,369.0,540.0,778.0,113.0,190.0,999.0,25.0,203.0,756.0,917.0,898.0,645.0,654.0,780.0,960.0,977.0,423.0,133.0,993.0,535.0,694.0,515.0,833.0,170.0,427.0,421.0,489.0,220.0,166.0,705.0,268.0,267.0,370.0,55.0,597.0,781.0,472.0,205.0,597.0,61.0,288.0,293.0,855.0,279.0,946.0,353.0,165.0,13.0,276.0,350.0,6.0,19.0,836.0,480.0,748.0,927.0,994.0,96...

In [14]:
val ma = dm1.map(_.toArray).take(dm1.count.toInt)

In [15]:
val localMat = Matrices.dense( dm1.count.toInt,
                                 dm1.take(1)(0).size,
                                 transpose(ma).flatten)

In [19]:
val resultado = rmat.multiply(localMat).rows

In [20]:
resultado.take(5)

Array([6867294.0,6358482.0,5845879.0,7062007.0,5306730.0,5181415.0,5728028.0,5025470.0,5929446.0,4353986.0,5390376.0,5125131.0,5882573.0,6611053.0,6028168.0,5719443.0,5333237.0,6207271.0,6184187.0,6259350.0,6977452.0,7829378.0,5402419.0,5305296.0,5684960.0,6430094.0,7274743.0,6779634.0,5967646.0,4019161.0,5940831.0,6216818.0,6451459.0,6053591.0,4884622.0,6644943.0,5672833.0,6604224.0,6378858.0,6280200.0,6331848.0,6342169.0,5052244.0,5476183.0,5985736.0,5427466.0,6291049.0,7804672.0,4560290.0,6881373.0,6100429.0,5257385.0,6623579.0,5507667.0,5327109.0,5626293.0,6485926.0,5624282.0,6630671.0,5810892.0,5618538.0,6196824.0,5918008.0,4149856.0,4903483.0,6348312.0,6195033.0,3776484.0,6020739.0,6012223.0,6186947.0,3734420.0,5245939.0,6915020....

Array([6867294.0,6358482.0,5845879.0,7062007.0,5306730.0,5181415.0,5728028.0,5025470.0,5929446.0,4353986.0,5390376.0,5125131.0,5882573.0,6611053.0,6028168.0,5719443.0,5333237.0,6207271.0,6184187.0,6259350.0,6977452.0,7829378.0,5402419.0,5305296.0,5684960.0,6430094.0,7274743.0,6779634.0,5967646.0,4019161.0,5940831.0,6216818.0,6451459.0,6053591.0,4884622.0,6644943.0,5672833.0,6604224.0,6378858.0,6280200.0,6331848.0,6342169.0,5052244.0,5476183.0,5985736.0,5427466.0,6291049.0,7804672.0,4560290.0,6881373.0,6100429.0,5257385.0,6623579.0,5507667.0,5327109.0,5626293.0,6485926.0,5624282.0,6630671.0,5810892.0,5618538.0,6196824.0,5918008.0,4149856.0,4903483.0,6348312.0,6195033.0,3776484.0,6020739.0,6012223.0,6186947.0,3734420.0,5245939.0,6915020....